export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_LOADING = 'AUTH_LOADING';
export const EDIT_USER = 'EDIT_USER';

export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CREATE_PROFILE = 'CREATE_PROFILE';

export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const SET_CURRENT_PICTURE = 'SET_CURRENT_PICTURE';
export const GET_ALL_PICTURES = 'GET_ALL_PICTURES';
export const LIKE_PICTURE = 'LIKE_PICTURE';
export const DELETE_PICTURE = 'DELETE_PICTURE';

export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const LOADING_PROFILES = 'LOADING_PROFILES';
export const PROFILES_ERROR = 'PROFILES_ERROR';
