export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_LOADING = 'AUTH_LOADING';
export const EDIT_USER = 'EDIT_USER';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const SET_CURRENT_PICTURE = 'SET_CURRENT_PICTURE';
export const SET_CURRENT_PICTURES = 'SET_CURRENT_PICTURES';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const LOGOUT = 'LOGOUT';

export const SET_PROFILE = 'SET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const SET_CONNECTION = 'SET_CONNECTION';
export const REDUCE_RATING = 'REDUCE_RATING';

export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const SET_PICTURE = 'SET_PICTURE';
export const GET_ALL_PICTURES = 'GET_ALL_PICTURES';
export const LIKE_PICTURE = 'LIKE_PICTURE';
export const DELETE_PICTURE = 'DELETE_PICTURE';
export const DELETE_LIKES = 'DELETE_LIKES';

export const SET_PROFILES = 'SET_PROFILES';
// export const SORT_PROFILES = 'SORT_PROFILES';
// export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const LOADING_PROFILES = 'LOADING_PROFILES';
export const PROFILES_ERROR = 'PROFILES_ERROR';

export const SAVE_TO_HISTORY = 'SAVE_TO_HISTORY';
export const LOADING_HISTORY = 'LOADING_HISTORY';
export const SET_VISITORS_HISTORY = 'SET_VISITORS_HISTORY';
export const SET_VISITED_HISTORY = 'SET_VISITED_HISTORY';
export const HISTORY_ERROR = 'HISTORY_ERROR';
export const CHAT_ERROR = 'CHAT_ERROR';

export const SET_ROOM_CHAT = 'SET_ROOM_CHAT';
export const LOADING_CHAT = 'LOADING_CHAT';
export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_PROFILE_CHATTING_WITH = 'SET_PROFILE_CHATTING_WITH';

export const SET_SOCKET = 'SET_SOCKET';
