module.exports = {
  // COMMUNITY_CHAT: 'COMMUNITY_CHAT',
  // USER_CONNECTED: 'USER_CONNECTED',
  // USER_DISCONNECTED: 'USER_DISCONNECTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  TYPING: 'TYPING',
  // VERIFY_USER: 'VERIFY_USER',
  JOIN_APP: 'JOIN_APP',
  LEAVE_APP: 'LEAVE_APP',
  JOIN_CHAT: 'JOIN_CHAT',
  NOTIFICATION_RECIEVED: 'NOTIFICATION_RECIEVED',
  LEAVE_CHAT: 'LEAVE_CHAT',
  LIKE: 'LIKE',
  PROFILE_CHECKED: 'PROFILE_CHECKED'
};
